name: CI - CiCd

on:
  workflow_dispatch: #Giver mulighed for at workflow kan kører manuelt
  pull_request:
    types: # Angiver hvilke typer af PR som workflow skal trigges på, kan fjernes for standard opsætning
      - opened
    branches: [ "master" ] #Navn på hoved branch
    paths: # Fjernes hvis projektet er monolitisk
      - "src/Cicd/**" #Sti til microservice her, fjernes hvis projektet er monolitisk

permissions:
  contents: read

env:
  DOTNET_VERSION: "10.0.x" #Target .Net version, skal matche projektes version
  SOLUTION_PATH: "CICD-Template.slnx" #Navn på din solution fil

jobs:
  Build-and-Test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Get Code
      uses: actions/checkout@v7

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
         dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore ${{ env.SOLUTION_PATH }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} 
        --configuration Release
        --no-restore

    - name: Test
      run: dotnet test ${{ env.SOLUTION_PATH }}
        --configuration Release
        --no-restore 
        --no-build 
        --verbosity normal